collections:
  - name: nginxinc.nginx_core
    version: 0.3.0
  - name: community.general
    version: 3.8.0
  - name: ansible.posix
    version: 1.3.0
  - name: community.docker  # Only required if you plan to use Molecule (see below)
    version: 2.0.0
  - name: debops.debops
