---
- name: update
  hosts: all
  gather_facts: false
  tasks:
  - name: Update
    command: "yum -y update"

- name: Install Apache on web and start service
  hosts: all
  gather_facts: false
  tasks: 
    - name: Install Apache
      yum:
        name: httpd
        state: latest
    - name: update port
      command: "sed -i 's/Listen 80/Listen 8081/g' /etc/httpd/conf/httpd.conf"
    - name: Start Apache service
      systemd: 
        name: httpd
        state: started
#    - name: Open TCP 8081 and 443
#      firewalld:
#        service: "{{ item }}"
#        permanent: yes
#        state: enabled
#        immediate: yes
#      loop: 
#        - 8081
#        - https

- name: Install MySQL and start service
  hosts: all
  gather_facts: false
  tasks: 
    - name: Install MySQL
      yum: 
        name: mysql-server
        state: latest
    - name: Start MySQL service
      systemd: 
        name: mysqld
        state: started
        enabled: yes
...
